"use client"

import { useState } from "react"
import { Building, Pencil, PiggyBank, Plus, X } from "lucide-react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { createAccount, deleteAccount, updateAccount } from "@/app/app/accounts/actions"

export interface ManagedAccount { id: string; name: string; type: string; balanceCents: number | null; balanceDate: string | null; transactionCount: number }

export function AccountManager({ accounts }: { accounts: ManagedAccount[] }) {
  const router = useRouter()
  const [editing, setEditing] = useState<ManagedAccount | "new" | null>(null)
  const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100)
  return <><div className="flex justify-end mb-5"><Button size="sm" onClick={() => setEditing("new")}><Plus className="h-4 w-4" /> Add account</Button></div>{accounts.length === 0 ? <div className="flex flex-col items-center justify-center py-16 text-center rounded-2xl border border-border bg-card"><div className="w-14 h-14 rounded-2xl bg-primary/10 flex items-center justify-center mb-4"><Building className="h-7 w-7 text-primary" /></div><h2 className="text-lg font-semibold">Add the account you use day to day</h2><p className="text-sm text-muted-foreground max-w-sm mt-2 mb-5">Its current balance anchors your forecast. You can add another checking or savings account whenever you need it.</p><Button onClick={() => setEditing("new")}><Plus className="h-4 w-4" /> Add your first account</Button></div> : <div className="grid sm:grid-cols-2 gap-4">{accounts.map((account) => <div key={account.id} className="rounded-2xl border border-border bg-card p-5"><div className="flex items-start justify-between gap-3"><div className="h-10 w-10 rounded-xl bg-primary/10 flex items-center justify-center">{account.type === "savings" ? <PiggyBank className="h-5 w-5 text-primary" /> : <Building className="h-5 w-5 text-primary" />}</div><Button variant="ghost" size="icon" onClick={() => setEditing(account)} aria-label={`Edit ${account.name}`}><Pencil className="h-4 w-4" /></Button></div><h2 className="font-semibold mt-4">{account.name}</h2><p className="text-xs text-muted-foreground capitalize mt-1">{account.type.replace("_", " ")} · {account.transactionCount} transactions</p><p className="text-2xl font-bold font-mono mt-4">{account.balanceCents === null ? "No balance" : money(account.balanceCents)}</p><p className="text-xs text-muted-foreground mt-1">{account.balanceDate ? `Balance as of ${new Date(`${account.balanceDate}T00:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}` : "Add a balance date"}</p></div>)}</div>}{editing && <AccountEditor account={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); router.refresh() }} />}</>
}

function AccountEditor({ account, onClose, onSaved }: { account: ManagedAccount | "new"; onClose: () => void; onSaved: () => void }) {
  const isNew = account === "new"
  const [name, setName] = useState(isNew ? "" : account.name)
  const [type, setType] = useState<"checking" | "savings">(isNew ? "checking" : account.type === "savings" ? "savings" : "checking")
  const [balance, setBalance] = useState(isNew || account.balanceCents === null ? "" : String(account.balanceCents / 100))
  const [balanceDate, setBalanceDate] = useState(isNew || !account.balanceDate ? new Date().toISOString().slice(0, 10) : account.balanceDate)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-labelledby="account-editor-title"><button className="absolute inset-0 bg-background/75 backdrop-blur-sm" onClick={onClose} aria-label="Close account editor" /><form className="relative w-full max-w-md rounded-2xl border border-border bg-card p-6 shadow-2xl space-y-4" onSubmit={async (event) => { event.preventDefault(); const cents = Math.round(Number(balance) * 100); if (!Number.isSafeInteger(cents)) { setError("Enter a valid current balance."); return } setSaving(true); const result = isNew ? await createAccount({ name, type, balanceCents: cents, balanceDate }) : await updateAccount({ accountId: account.id, name, balanceCents: cents, balanceDate }); setSaving(false); if (!result.ok) { setError(result.message); return } onSaved() }}><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[0.14em] text-primary font-mono mb-1">{isNew ? "New account" : "Account details"}</p><h2 id="account-editor-title" className="text-xl font-bold">{isNew ? "Add an account" : `Edit ${account.name}`}</h2></div><Button type="button" variant="ghost" size="icon" onClick={onClose} aria-label="Close"><X className="h-4 w-4" /></Button></div><Field label="Account name" value={name} onChange={setName} placeholder="Everyday checking" /><div><label htmlFor="account-type" className="text-xs text-muted-foreground block mb-1.5">Account type</label><select id="account-type" value={type} disabled={!isNew} onChange={(event) => setType(event.target.value as "checking" | "savings")} className="w-full rounded-lg border border-input bg-background px-3 py-2 text-sm disabled:opacity-60"><option value="checking">Checking</option><option value="savings">Savings</option></select></div><Field label="Current balance" value={balance} onChange={setBalance} type="number" placeholder="0.00" /><Field label="Balance as of" value={balanceDate} onChange={setBalanceDate} type="date" />{error && <p className="text-sm text-destructive" role="alert">{error}</p>}<Button type="submit" className="w-full" disabled={saving}>{saving ? "Saving…" : isNew ? "Add account" : "Save changes"}</Button>{!isNew && <div className="border-t border-border pt-4"><Button type="button" variant="outline" className="w-full text-destructive" disabled={saving || account.transactionCount > 0} onClick={async () => { if (!window.confirm(`Remove ${account.name}?`)) return; setSaving(true); const result = await deleteAccount(account.id); setSaving(false); if (!result.ok) { setError(result.message); return } onSaved() }}>Remove account</Button>{account.transactionCount > 0 && <p className="text-[11px] text-muted-foreground mt-2">Accounts with transaction history can’t be removed because that would break traceability.</p>}</div>}</form></div>
}

function Field({ label, value, onChange, type = "text", placeholder }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string }) { const id = `account-${label.toLowerCase().replace(/\s+/g, "-")}`; return <div><label htmlFor={id} className="text-xs text-muted-foreground block mb-1.5">{label}</label><input id={id} value={value} onChange={(event) => onChange(event.target.value)} type={type} step={type === "number" ? "0.01" : undefined} placeholder={placeholder} required className="w-full rounded-lg border border-input bg-background px-3 py-2 text-sm" /></div> }
