"use client"

import { useEffect, useState } from "react"
import Link from "next/link"
import { ArrowRight, Check, ChevronRight, CircleHelp, Eye, ShieldCheck, Sparkles, TrendingDown, WalletCards } from "lucide-react"

const tabs = [
  { id: "forecast", label: "Forecast" },
  { id: "scenario", label: "Scenario Planner" },
  { id: "recurring", label: "Recurring" },
  { id: "transfers", label: "Transfers" },
] as const

type TabId = (typeof tabs)[number]["id"]

const forecastPoints = [
  { x: 0, y: 56 }, { x: 9, y: 60 }, { x: 18, y: 57 }, { x: 27, y: 65 },
  { x: 36, y: 72 }, { x: 45, y: 82 }, { x: 54, y: 76 }, { x: 64, y: 84 },
  { x: 73, y: 48 }, { x: 82, y: 42 }, { x: 91, y: 38 }, { x: 100, y: 35 },
]

function linePath(points: typeof forecastPoints) {
  return points.map((point, index) => `${index === 0 ? "M" : "L"} ${point.x} ${point.y}`).join(" ")
}

function ProductPreview({ tab }: { tab: TabId }) {
  if (tab === "scenario") return <div className="space-y-4"><div className="flex items-center justify-between"><p className="text-sm font-medium text-[#111827]">Test a decision</p><span className="rounded-full bg-[#FCF0E9] px-2.5 py-1 text-[11px] font-medium text-[#B85B35]">What if?</span></div><div className="grid grid-cols-2 gap-3"><div className="rounded-xl border border-[#E7DDD1] bg-white p-3"><p className="text-[11px] text-[#73766F]">Purchase</p><p className="mt-1 font-medium text-[#111827]">Laptop</p><p className="mt-2 font-mono text-lg text-[#111827]">$2,000</p></div><div className="rounded-xl border border-[#E7DDD1] bg-white p-3"><p className="text-[11px] text-[#73766F]">Earliest clear</p><p className="mt-1 font-medium text-[#111827]">Aug 14</p><p className="mt-2 text-xs text-[#2D7A55]">$620 above buffer</p></div></div><div className="rounded-xl bg-[#F8F1E8] p-3 text-sm leading-relaxed text-[#374151]">Buying today creates a tight day on <span className="font-medium text-[#111827]">Aug 12</span>. Rent and the card payment arrive first.</div></div>
  if (tab === "recurring") return <div className="space-y-3"><div className="flex items-center justify-between"><p className="text-sm font-medium text-[#111827]">3 recurring patterns found</p><span className="text-xs text-[#73766F]">Review once</span></div>{[{ name: "Rent", amount: "−$1,750", status: "confirmed", color: "#2D7A55" }, { name: "Payroll", amount: "+$1,950", status: "confirmed", color: "#2D7A55" }, { name: "Electricity", amount: "~−$117", status: "estimated", color: "#B7791F" }].map((item) => <div key={item.name} className="flex items-center gap-3 rounded-xl border border-[#EFE7DB] bg-white px-3 py-3"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: item.color }} /><span className="flex-1"><span className="block text-sm font-medium text-[#111827]">{item.name}</span><span className="block text-[11px] capitalize text-[#73766F]">{item.status}</span></span><span className="font-mono text-sm" style={{ color: item.color }}>{item.amount}</span></div>)}</div>
  if (tab === "transfers") return <div className="space-y-4"><div><p className="text-sm font-medium text-[#111827]">Purchases explain what you spent.</p><p className="mt-1 text-xs leading-relaxed text-[#73766F]">The card payment is when cash leaves checking.</p></div><div className="relative space-y-2 rounded-xl border border-[#EFE7DB] bg-white p-3"><div className="flex items-center justify-between text-sm"><span className="font-medium text-[#111827]">Checking</span><span className="font-mono text-[#111827]">−$1,200</span></div><div className="mx-auto h-5 w-px border-l border-dashed border-[#C96B43]" /><div className="flex items-center justify-between text-sm"><span className="font-medium text-[#111827]">Card payment</span><span className="font-mono text-[#111827]">+$1,200</span></div><div className="mt-3 flex items-center gap-2 rounded-lg bg-[#F0F8F3] px-2.5 py-2 text-xs text-[#2D7A55]"><Check className="h-3.5 w-3.5" />Linked as a transfer</div></div></div>
  return <div className="space-y-4"><div className="flex items-center justify-between"><div><p className="text-sm font-medium text-[#111827]">Projected balance</p><p className="text-xs text-[#73766F]">Today → Aug 25</p></div><span className="rounded-full bg-[#F0F8F3] px-2.5 py-1 text-[11px] font-medium text-[#2D7A55]">Clear</span></div><div className="rounded-xl border border-[#EFE7DB] bg-white p-3"><svg viewBox="0 0 100 100" className="h-36 w-full overflow-visible" preserveAspectRatio="none"><line x1="0" x2="100" y1="72" y2="72" stroke="#D7E7DB" strokeDasharray="2 3" /><path d={linePath(forecastPoints)} fill="none" stroke="#C96B43" strokeWidth="2.2" pathLength="100" strokeDasharray="100" strokeDashoffset="0" /><circle cx="64" cy="84" r="3" fill="#C96B43" /><text x="66" y="96" fontSize="5" fill="#B85B35">low point</text></svg><div className="mt-1 flex justify-between text-[10px] text-[#73766F]"><span>Today</span><span>Aug 12 · $3,100</span><span>Aug 25</span></div></div><div className="flex items-center justify-between rounded-xl bg-[#F8F1E8] px-3 py-2.5"><span className="text-xs text-[#374151]">Safe to Spend</span><span className="font-mono text-sm font-medium text-[#2D7A55]">$3,100</span></div></div>
}

function AhaForecast() {
  const [step, setStep] = useState(0)
  const events = [{ label: "Rent", amount: "−$1,750" }, { label: "Insurance", amount: "−$180" }, { label: "Card payment", amount: "−$1,000" }]
  useEffect(() => {
    const timer = window.setInterval(() => setStep((current) => (current + 1) % 4), 1800)
    return () => window.clearInterval(timer)
  }, [])
  const values = ["$5,500", "$3,750", "$3,570", "$2,570"]
  return <div className="rounded-[28px] border border-[#EFE7DB] bg-white p-5 shadow-[0_18px_50px_rgba(28,28,34,0.08)] sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-[0.16em] text-[#C96B43]">Example forecast</p><p className="mt-1 text-sm text-[#73766F]">One balance, built through the events that shape it.</p></div><span className="font-mono text-3xl font-medium text-[#111827] transition-all duration-500">{values[step]}</span></div><div className="mt-6 grid gap-6 lg:grid-cols-[1.25fr_0.75fr] lg:items-center"><div className="rounded-2xl bg-[#FCF9F5] p-4"><svg viewBox="0 0 100 56" className="h-48 w-full overflow-visible" preserveAspectRatio="none"><line x1="0" x2="100" y1="42" y2="42" stroke="#D6E5D9" strokeDasharray="2 3" /><path d="M0 12 C15 12 19 18 31 21 S52 33 63 40 S76 44 86 28 S94 20 100 19" fill="none" stroke="#C96B43" strokeWidth="1.6" pathLength="100" strokeDasharray="100" strokeDashoffset={Math.max(0, 100 - (step + 1) * 25)} className="transition-[stroke-dashoffset] duration-700 ease-out" /><circle cx={[0, 31, 52, 63][step]} cy={[12, 21, 33, 40][step]} r="2.5" fill="#C96B43" className="transition-all duration-500" /><text x="2" y="53" fontSize="4" fill="#73766F">Today</text><text x="77" y="53" fontSize="4" fill="#73766F">Aug 3</text></svg><div className="mt-2 flex items-center justify-between text-[11px] text-[#73766F]"><span>Balance moves as each event arrives</span><span className="font-mono">$0 floor</span></div></div><div className="space-y-2">{events.map((event, index) => <div key={event.label} className={`flex items-center justify-between rounded-xl border px-3 py-3 transition-all duration-500 ${index < step ? "border-[#E7C9B8] bg-[#FCF0E9]" : "border-[#EFE7DB] bg-white"}`}><span className="flex items-center gap-2 text-sm text-[#374151]"><span className={`h-2 w-2 rounded-full ${index < step ? "bg-[#C96B43]" : "bg-[#D7D9D5]"}`} />{event.label}</span><span className="font-mono text-sm text-[#111827]">{event.amount}</span></div>)}<p className="pt-2 text-sm leading-relaxed text-[#374151]">{step === 3 ? <><span className="font-medium text-[#111827]">$2,570 on August 3.</span> FlowSight shows the tight spot before it arrives.</> : "The forecast makes the cause visible, one event at a time."}</p></div></div></div>
}

export default function DesignSampleLanding() {
  const [tab, setTab] = useState<TabId>("forecast")
  const [ahead, setAhead] = useState(false)
  return <main className="fs-landing min-h-screen bg-[#FFFDFC] text-[#111827]">
    <nav className="sticky top-0 z-20 border-b border-[#E7DDD1]/70 bg-[#FFFDFC]/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5 sm:px-8"><Link href="/" className="flex items-center gap-2 text-sm font-medium"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#111827] text-lg text-[#FFFDFC]">↗</span>FlowSight</Link><div className="hidden items-center gap-7 text-sm text-[#73766F] md:flex"><a href="#aha">Forecast</a><a href="#features">How it works</a><a href="#security">Security</a></div><div className="flex items-center gap-3"><Link href="/sign-in" className="hidden text-sm text-[#73766F] hover:text-[#111827] sm:inline">Sign in</Link><Link href="/sign-up" className="fs-brand-action rounded-lg px-4 py-2 text-sm font-medium">Join beta</Link></div></div></nav>

    <section className="mx-auto grid max-w-6xl gap-12 px-5 pb-20 pt-16 sm:px-8 sm:pt-24 lg:grid-cols-[0.88fr_1.12fr] lg:items-center lg:pb-28"><div><p className="mb-5 text-xs font-medium uppercase tracking-[0.18em] text-[#C96B43]">Cash-flow clarity</p><h1 className="max-w-xl text-5xl leading-[1.03] sm:text-6xl">See what’s next for your <span className="text-[#C96B43]">money.</span></h1><p className="mt-6 max-w-lg text-lg text-[#374151]">Most finance apps organize what already happened. FlowSight shows what the next few weeks may hold—and what to do if money gets tight.</p><div className="mt-8 flex flex-wrap items-center gap-3"><Link href="/sign-up" className="fs-brand-action rounded-lg px-5 py-3 text-sm font-medium">Start with your numbers <ArrowRight className="ml-1 inline h-4 w-4" /></Link><a href="#aha" className="rounded-lg border border-[#D8D2CA] bg-white px-5 py-3 text-sm font-medium text-[#111827] hover:border-[#C96B43]">See the forecast</a></div><p className="mt-4 text-xs text-[#73766F]">CSV or manual setup · no bank connection required</p></div><div className="relative rounded-[28px] bg-[#FCF9F5] p-4 shadow-[0_18px_50px_rgba(28,28,34,0.08)] sm:p-6"><div className="rounded-2xl border border-[#EFE7DB] bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-xs text-[#73766F]">Good morning, Soundarya</p><p className="mt-2 text-2xl font-medium">Your next 30 days</p></div><span className="rounded-full bg-[#F0F8F3] px-2.5 py-1 text-xs font-medium text-[#2D7A55]">Clear</span></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#FCF9F5] p-3"><p className="text-xs text-[#73766F]">Current balance</p><p className="mt-2 font-mono text-xl text-[#111827]">$3,900</p></div><div className="rounded-xl bg-[#F0F8F3] p-3"><p className="text-xs text-[#73766F]">Safe to Spend</p><p className="mt-2 font-mono text-xl text-[#2D7A55]">$3,100</p></div></div><div className="mt-4 rounded-xl border border-[#EFE7DB] p-3"><div className="flex items-center justify-between text-xs text-[#73766F]"><span>Projected balance</span><span>Today → Aug 25</span></div><svg viewBox="0 0 100 42" className="mt-3 h-28 w-full" preserveAspectRatio="none"><path d="M0 12 C20 13 24 20 35 18 S50 28 62 30 S72 31 80 18 S92 16 100 14" fill="none" stroke="#C96B43" strokeWidth="1.8" /><line x1="0" x2="100" y1="32" y2="32" stroke="#D7E7DB" strokeDasharray="2 3" /></svg></div><div className="mt-4 flex items-center gap-2 text-xs text-[#374151]"><span className="h-2 w-2 rounded-full bg-[#C96B43]" />Rent and card payment are the next moments to watch.</div></div></div></section>

    <section id="aha" className="bg-[#F8F1E8] px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl"><div className="mx-auto mb-10 max-w-2xl text-center"><p className="text-xs font-medium uppercase tracking-[0.18em] text-[#C96B43]">The moment it clicks</p><h2 className="mt-4 text-4xl leading-tight sm:text-5xl">A forecast you can <span className="text-[#C96B43]">follow.</span></h2><p className="mt-4 text-lg text-[#374151]">See the balance change as the events behind it arrive. No black box, no mystery.</p></div><AhaForecast /></div></section>

    <section id="features" className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl"><div className="max-w-2xl"><p className="text-xs font-medium uppercase tracking-[0.18em] text-[#C96B43]">Inside FlowSight</p><h2 className="mt-4 text-4xl leading-tight sm:text-5xl">One picture of what’s <span className="text-[#C96B43]">ahead.</span></h2><p className="mt-4 text-lg text-[#374151]">Every view answers a different question, with the same numbers underneath.</p></div><div className="mt-10 grid gap-8 lg:grid-cols-[0.7fr_1.3fr] lg:items-start"><div className="space-y-2">{tabs.map((item) => <button key={item.id} type="button" onClick={() => setTab(item.id)} className={`flex w-full items-center justify-between rounded-xl px-4 py-4 text-left text-sm transition ${tab === item.id ? "bg-[#111827] text-white" : "text-[#374151] hover:bg-[#FCF9F5]"}`}><span>{item.label}</span><ChevronRight className={`h-4 w-4 transition-transform ${tab === item.id ? "translate-x-1" : ""}`} /></button>)}</div><div className="rounded-[28px] bg-[#FCF9F5] p-4 sm:p-7"><ProductPreview tab={tab} /></div></div></div></section>

    <section className="border-y border-[#E7DDD1] bg-[#FCF9F5] px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-medium uppercase tracking-[0.18em] text-[#C96B43]">Built for real life</p><h2 className="mt-4 text-4xl leading-tight sm:text-5xl">Know what FlowSight <span className="text-[#C96B43]">knows.</span></h2></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="fs-interactive rounded-2xl border border-[#EFE7DB] bg-white p-6"><WalletCards className="h-5 w-5 text-[#C96B43]" /><h3 className="mt-5 text-xl font-medium">Confirmed vs. estimated</h3><p className="mt-2 text-sm text-[#73766F]">Stable rent and variable electricity never look like the same kind of fact.</p><div className="mt-6 flex gap-2"><span className="rounded-full bg-[#F0F8F3] px-3 py-1.5 text-xs text-[#2D7A55]">Confirmed</span><span className="rounded-full bg-[#FFF5D9] px-3 py-1.5 text-xs text-[#B7791F]">Estimated</span></div></div><div className="fs-interactive rounded-2xl border border-[#EFE7DB] bg-white p-6"><TrendingDown className="h-5 w-5 text-[#C96B43]" /><h3 className="mt-5 text-xl font-medium">Timing, not just totals</h3><p className="mt-2 text-sm text-[#73766F]">See the week a paycheck, rent, and a card payment all meet.</p><div className="mt-6 flex items-end gap-2" aria-label="Income timing illustration">{[18, 30, 18, 42, 18, 26, 18].map((height, index) => <span key={index} className={`w-5 rounded-t ${index === 3 ? "bg-[#C96B43]" : "bg-[#D7E7DB]"}`} style={{ height }} />)}</div></div><div className="fs-interactive rounded-2xl border border-[#EFE7DB] bg-white p-6"><Eye className="h-5 w-5 text-[#C96B43]" /><h3 className="mt-5 text-xl font-medium">Show your work</h3><p className="mt-2 text-sm text-[#73766F]">Tap any result and see the balance, activity, buffer, and assumptions behind it.</p><div className="mt-6 rounded-xl bg-[#FCF9F5] p-3 text-xs text-[#374151]">$3,840 balance + $420 activity = <span className="font-mono font-medium text-[#111827]">$4,260 opening</span></div></div><div className="fs-interactive rounded-2xl border border-[#EFE7DB] bg-white p-6"><Sparkles className="h-5 w-5 text-[#C96B43]" /><h3 className="mt-5 text-xl font-medium">Income that doesn’t fit one mold</h3><p className="mt-2 text-sm text-[#73766F]">Regular paychecks, freelance invoices, or both—each pattern gets its own honest range.</p><div className="mt-6 flex items-end gap-2">{[24, 38, 21, 46, 29, 54].map((height, index) => <span key={index} className={`w-5 rounded-t ${index % 2 === 0 ? "bg-[#2D7A55]" : "bg-[#C96B43]"}`} style={{ height }} />)}</div></div></div></div></section>

    <section className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-[#C96B43]">A clearer question</p><h2 className="mt-4 text-4xl leading-tight sm:text-5xl">Stop looking backward. <span className="text-[#C96B43]">Start planning forward.</span></h2><p className="mt-5 max-w-lg text-lg text-[#374151]">Most tools organize what already happened. FlowSight shows what the next few weeks may hold—and what to do if money gets tight.</p></div><div className="rounded-[28px] bg-[#111827] p-5 text-white sm:p-7"><div className="flex gap-2 rounded-xl bg-white/10 p-1 text-sm"><button type="button" onClick={() => setAhead(false)} className={`flex-1 rounded-lg px-3 py-2 ${!ahead ? "bg-white text-[#111827]" : "text-white/65"}`}>Looking back</button><button type="button" onClick={() => setAhead(true)} className={`flex-1 rounded-lg px-3 py-2 ${ahead ? "bg-white text-[#111827]" : "text-white/65"}`}>Looking ahead</button></div><div className="mt-8"><p className="text-sm text-white/60">{ahead ? "What FlowSight tells you" : "What you’re used to"}</p><div className="mt-4 space-y-3">{(ahead ? ["You have $820 safe to spend until the 18th", "Rent and insurance create a low point on August 3", "A late invoice changes the plan—not your history"] : ["You spent $200 on dining last month", "An alert arrived after the overdraft", "A fixed budget ignored your actual timing"]).map((item) => <div key={item} className={`flex items-start gap-3 rounded-xl border p-3 text-sm ${ahead ? "border-[#2D7A55]/35 bg-[#2D7A55]/10" : "border-white/10 bg-white/5 text-white/75"}`}><span className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full ${ahead ? "bg-[#2D7A55]" : "bg-white/10"}`}>{ahead ? <Check className="h-3.5 w-3.5" /> : "–"}</span>{item}</div>)}</div></div></div></div></section>

    <section id="security" className="bg-[#F8F1E8] px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-medium uppercase tracking-[0.18em] text-[#C96B43]">Private by design</p><h2 className="mt-4 text-4xl leading-tight sm:text-5xl">Start with your numbers, <span className="text-[#C96B43]">stay in control.</span></h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[{ icon: ShieldCheck, title: "No bank connection required", copy: "Import a CSV or add details manually. Your login never needs to leave your bank." }, { icon: CircleHelp, title: "Every number has a reason", copy: "Confirmed events, estimates, ranges, and assumptions stay visible." }, { icon: WalletCards, title: "Nothing changes without you", copy: "Scenarios, transfers, and recurring patterns wait for your confirmation." }].map(({ icon: Icon, title, copy }) => <div key={title} className="rounded-2xl border border-[#EFE7DB] bg-white p-6"><Icon className="h-5 w-5 text-[#C96B43]" /><h3 className="mt-5 text-lg font-medium">{title}</h3><p className="mt-2 text-sm leading-relaxed text-[#73766F]">{copy}</p></div>)}</div></div></section>

    <section className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-4xl rounded-[32px] bg-[#111827] px-6 py-16 text-center text-white sm:px-12"><p className="text-xs font-medium uppercase tracking-[0.18em] text-[#E2A080]">See what’s next</p><h2 className="mt-4 text-4xl leading-tight sm:text-5xl">Stop guessing. <span className="text-[#E2A080]">Start knowing.</span></h2><p className="mx-auto mt-5 max-w-xl text-base leading-relaxed text-white/70">Bring your numbers. FlowSight will show you the days that matter before they arrive.</p><Link href="/sign-up" className="mt-8 inline-flex items-center rounded-lg bg-[#FFFDFC] px-5 py-3 text-sm font-medium text-[#111827] hover:bg-[#F8F1E8]">Join the beta <ArrowRight className="ml-2 h-4 w-4" /></Link></div></section>
    <footer className="border-t border-[#E7DDD1] px-5 py-8 text-xs text-[#73766F] sm:px-8"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-3"><span className="font-medium text-[#111827]">FlowSight</span><span>Forward-looking cash-flow clarity.</span><span>Design sample · not the live landing page</span></div></footer>
  </main>
}
