"use client"

import { useState } from "react"
import { Download, Save, Trash2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Card, CardContent } from "@/components/ui/card"
import { deleteFinancialData, savePreferences, type PersonalizationPreferences } from "@/app/app/settings/actions"
import { createClient } from "@/lib/supabase/client"

export function SettingsPreferences({ initial }: { initial: PersonalizationPreferences }) {
  const [preferences, setPreferences] = useState(initial)
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState<string | null>(null)
  const [deleteConfirmation, setDeleteConfirmation] = useState("")
  const [deleting, setDeleting] = useState(false)
  const update = <K extends keyof PersonalizationPreferences>(key: K, value: PersonalizationPreferences[K]) => setPreferences((current) => ({ ...current, [key]: value }))

  return <div className="space-y-6">
    <Card><CardContent className="pt-6 space-y-5"><div><h3 className="font-semibold">Forecast preferences</h3><p className="text-sm text-muted-foreground mt-1">Choose how FlowSight frames your personal cash-flow outlook.</p></div><div className="space-y-2"><Label htmlFor="buffer">Safety buffer</Label><div className="relative max-w-[220px]"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground font-mono">$</span><Input id="buffer" type="number" min={0} step={50} value={preferences.safetyBufferCents / 100} onChange={(event) => update("safetyBufferCents", Math.round(Number(event.target.value) * 100))} className="pl-7 font-mono" /></div><p className="text-xs text-muted-foreground">The amount you prefer to keep available. This is not a savings goal.</p></div><div className="grid sm:grid-cols-2 gap-4"><PreferenceSelect label="Dashboard emphasis" value={preferences.dashboardEmphasis} onChange={(value) => update("dashboardEmphasis", value as PersonalizationPreferences["dashboardEmphasis"])} options={[['status','Status first — Am I okay?'],['calendar','Calendar first — What happens next?'],['decision','Decision first — What can I spend?']]} /><PreferenceSelect label="Information density" value={preferences.dashboardDensity} onChange={(value) => update("dashboardDensity", value as PersonalizationPreferences["dashboardDensity"])} options={[['comfortable','Comfortable'],['compact','Compact']]} /></div><label className="flex items-start gap-3 rounded-xl border border-border p-4"><input type="checkbox" checked={preferences.showSpendingHistory} onChange={(event) => update("showSpendingHistory", event.target.checked)} className="mt-1" /><span><span className="block text-sm font-medium">Show spending history on Dashboard</span><span className="block text-xs text-muted-foreground mt-1">Off by default so the Dashboard stays focused on what happens next.</span></span></label></CardContent></Card>

    <Card><CardContent className="pt-6 space-y-5"><div><h3 className="font-semibold">Personal alerts</h3><p className="text-sm text-muted-foreground mt-1">Choose which forecast changes deserve your attention.</p></div><div className="space-y-2"><AlertToggle checked={preferences.alertSafetyBuffer} onChange={(value) => update("alertSafetyBuffer", value)} title="Balance below safety buffer" detail="When the forecast first drops below your preferred minimum." /><AlertToggle checked={preferences.alertKnownBill} onChange={(value) => update("alertKnownBill", value)} title="Important known bill approaching" detail="A reminder before a confirmed bill puts pressure on your balance." /><AlertToggle checked={preferences.alertEstimateReview} onChange={(value) => update("alertEstimateReview", value)} title="Estimate needs confirmation" detail="When an estimated amount or date could materially affect the forecast." /><AlertToggle checked={preferences.alertStaleBalance} onChange={(value) => update("alertStaleBalance", value)} title="Current balance needs an update" detail="When the forecast anchor may no longer reflect your actual balance." /></div><PreferenceSelect label="Let me know" value={String(preferences.alertLeadDays)} onChange={(value) => update("alertLeadDays", Number(value))} options={[['0','On the day'],['1','1 day before'],['3','3 days before'],['7','1 week before']]} /></CardContent></Card>

    {message && <p className="text-sm text-muted-foreground" role="status">{message}</p>}<Button disabled={saving} onClick={async () => { setSaving(true); setMessage(null); const result = await savePreferences(preferences); setSaving(false); setMessage(result.ok ? "Your preferences are saved." : result.message) }}><Save className="h-4 w-4" /> {saving ? "Saving…" : "Save preferences"}</Button>

    <Card><CardContent className="pt-6 space-y-5"><div><h3 className="font-semibold">Your data</h3><p className="text-sm text-muted-foreground mt-1">Download a copy whenever you like, or remove your financial information from FlowSight.</p></div><a href="/api/data-export" download className="inline-flex h-9 items-center justify-center gap-2 rounded-md border border-input bg-background px-4 text-sm font-medium shadow-xs hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><Download className="h-4 w-4" /> Download my data</a><div className="rounded-xl border border-destructive/30 bg-destructive/[0.04] p-4 space-y-3"><div><h4 className="text-sm font-semibold">Delete financial data</h4><p className="text-xs text-muted-foreground mt-1">This permanently removes your accounts, transactions, recurring events, and preferences. It does not delete your sign-in identity.</p></div><div><Label htmlFor="delete-confirmation">Type DELETE to confirm</Label><Input id="delete-confirmation" value={deleteConfirmation} onChange={(event) => setDeleteConfirmation(event.target.value)} className="mt-2 max-w-[240px]" autoComplete="off" /></div><Button variant="destructive" disabled={deleting || deleteConfirmation !== "DELETE"} onClick={async () => { if (!window.confirm("Permanently delete all of your financial data?")) return; setDeleting(true); setMessage(null); const result = await deleteFinancialData(); if (!result.ok) { setDeleting(false); setMessage(result.message); return } await createClient().auth.signOut(); window.location.assign("/") }}><Trash2 className="h-4 w-4" /> {deleting ? "Deleting…" : "Delete financial data"}</Button></div></CardContent></Card>
  </div>
}

function AlertToggle({ checked, onChange, title, detail }: { checked: boolean; onChange: (value: boolean) => void; title: string; detail: string }) { return <label className="flex items-start gap-3 rounded-xl border border-border p-4 cursor-pointer"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="mt-1" /><span><span className="block text-sm font-medium">{title}</span><span className="block text-xs text-muted-foreground mt-1">{detail}</span></span></label> }
function PreferenceSelect({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: Array<[string,string]> }) { return <div><Label className="mb-2 block">{label}</Label><select value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm">{options.map(([optionValue, optionLabel]) => <option key={optionValue} value={optionValue}>{optionLabel}</option>)}</select></div> }
