import type { Metadata } from "next"
import { notFound } from "next/navigation"
import { ArticleShell, Callout, LearnSection } from "@/components/learn-shell"
import { CardFlowIllustration, CsvIllustration, ForecastMathIllustration, SafeToSpendIllustration, TroubleshootingIllustration } from "@/components/learn-illustrations"

const titles: Record<string,string> = {
  forecast: "How your forecast is calculated",
  "safe-to-spend": "Safe to Spend explained",
  "credit-cards": "Credit cards and transfers",
  "csv-import": "Importing a CSV",
  troubleshooting: "Why does my forecast look wrong?",
}

export function generateStaticParams() { return Object.keys(titles).map((slug)=>({slug})) }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata> { const {slug}=await params; return titles[slug]?{title:titles[slug]}:{} }

export default async function LearnArticle({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params
  if (!titles[slug]) notFound()
  if (slug === "forecast") return <ForecastArticle />
  if (slug === "safe-to-spend") return <SafeArticle />
  if (slug === "credit-cards") return <CardsArticle />
  if (slug === "csv-import") return <CsvArticle />
  return <TroubleshootingArticle />
}

function ForecastArticle() { return <ArticleShell eyebrow="Forecasting" title="How your forecast is calculated" intro="Cusp simulates your balance one day at a time using the financial information currently available."><ForecastMathIllustration /><LearnSection id="daily-calculation" title="A daily cash-flow simulation"><p>The forecast starts with the latest balance for each included checking or savings account. It adds income and subtracts bills, transactions, and card payments on their expected dates. Each day’s ending balance becomes the next day’s opening balance.</p><Callout><strong>Simple version:</strong> opening balance + income − bills and spending = ending balance. The important part is when each event happens.</Callout></LearnSection><LearnSection id="confirmed-and-estimated" title="Confirmed and estimated activity"><p><strong>Confirmed</strong> means the amount and timing were explicitly provided or supported by a stable pattern you approved. <strong>Estimated</strong> means the amount, date, or both may change.</p><p>A manually entered fixed paycheck can have a confirmed amount and an estimated date. A variable electricity bill may have both an estimated amount and date. Reviewing an estimate promotes it when you know the real information.</p></LearnSection><LearnSection id="limitations" title="What Cusp cannot see"><p>Cusp cannot include cash purchases, accounts you have not added, transactions you have not imported, or future changes you have not told it about. Its answer is only as current as the balance and activity supplied.</p></LearnSection></ArticleShell> }

function SafeArticle() { return <ArticleShell eyebrow="Safe to Spend" title="Safe to Spend explained" intro="Safe to Spend estimates what remains available after protecting your commitments and chosen cushion at the forecast’s lowest point."><SafeToSpendIllustration /><LearnSection id="formula" title="The formula"><p><strong>Safe to Spend = lowest projected balance − safety buffer.</strong> If that result is below zero, Cusp shows $0 rather than suggesting additional spending.</p></LearnSection><LearnSection id="worked-example" title="A worked example"><p>Your current balance might be $4,200, but rent and other activity could bring the 30-day low to $1,901. With a $1,000 buffer, Safe to Spend is $901—not $3,200—because the calculation protects the tightest day ahead.</p></LearnSection><LearnSection id="no-buffer" title="When no buffer is set"><p>Cusp uses $0 as the floor and says so clearly. A scenario can technically fit while leaving only a few dollars, so the resulting low balance remains visible. Choosing “Keep using $0” records that as a deliberate preference.</p></LearnSection></ArticleShell> }

function CardsArticle() { return <ArticleShell eyebrow="Credit cards" title="Credit cards and transfers" intro="Cusp separates what you spent from when money actually leaves checking, preventing the same purchase from being counted twice."><CardFlowIllustration /><LearnSection id="purchases-and-payments" title="Purchases explain spending; payments move cash"><p>A $60 grocery purchase on a card counts as spending and increases what the card is owed. It does not reduce checking that day. The later card payment is the cash event in the checking forecast.</p></LearnSection><LearnSection id="payment-estimates" title="How payment estimates work"><p>With no card history, Cusp uses the current balance owed as a cold-start estimate. Once transactions exist, recorded charges and known card-funded bills shape the next payment. If the statement closing day is unknown, the cycle remains clearly estimated.</p></LearnSection><LearnSection id="unmatched-payments" title="Matching prevents double-counting"><p>A matching positive and negative amount across two accounts on the same or adjacent day becomes a transfer suggestion. Confirming it excludes both sides from income and spending. A card-side “Payment Received” without its checking counterpart appears as <strong>Card payment · Source not matched</strong> until the other side arrives.</p></LearnSection></ArticleShell> }

function CsvArticle() { return <ArticleShell eyebrow="Connection-free import" title="Importing a CSV" intro="Cusp reads common bank-export formats locally in the import flow and lets you review everything before it is saved."><CsvIllustration /><LearnSection id="supported-columns" title="What the file needs"><p>A file needs a date, description, and either one signed amount column or separate debit and credit columns. Cusp supports common date and money formats, quoted descriptions, and comma or semicolon delimiters.</p></LearnSection><LearnSection id="direction" title="How money direction is interpreted"><p>Negative signed amounts are money out; positive amounts are money in. For split files, debit and credit columns determine direction. If a positive-only export is ambiguous, Cusp asks for help instead of guessing.</p></LearnSection><LearnSection id="duplicates" title="Duplicates and review"><p>Rows already imported from the same file are skipped. Invalid rows are identified by row number and are not saved. Recurring patterns are proposed separately so you can confirm, replace, or ignore them.</p></LearnSection><LearnSection id="no-connection" title="No bank connection required"><p>CSV import is connection-free. You choose the file and account, review the detected columns and transactions, and decide what enters Cusp.</p></LearnSection></ArticleShell> }

function TroubleshootingArticle() { return <ArticleShell eyebrow="Troubleshooting" title="Why does my forecast look wrong?" intro="Most surprising forecasts come from stale or incomplete inputs. Check these areas before assuming the calculation is broken."><TroubleshootingIllustration /><LearnSection id="stale-balance" title="Start with the current balance"><p>If the balance is old, newer activity may not be reflected accurately. Update the account balance and its date, then review the recalculated low point.</p></LearnSection><LearnSection id="missing-activity" title="Look for missing activity"><p>Check for unimported accounts, missing card purchases, cash spending, or a recurring item that is paused or still awaiting confirmation. Cusp cannot include activity it has not received.</p></LearnSection><LearnSection id="transfers" title="Check transfers and card payments"><p>If a transfer is counted as spending or income, review the suggested account match. Card-side payments can remain unmatched until the corresponding checking withdrawal is available.</p></LearnSection><LearnSection id="estimates" title="Review the assumptions"><p>Open Show Your Work to see confirmed events, estimates, freshness, and card-payment evidence. Update an estimated date or amount when better information becomes available.</p></LearnSection></ArticleShell> }
